[package]
name = "serde-zap"
version = "0.1.1"
edition = "2024"
description = "The fastest binary serializer for serde's standard traits — independently benchmarked."
license = "MIT OR Apache-2.0"
repository = "https://github.com/xangelix/serde-zap"
keywords = ["serde", "serialization", "binary", "encoding", "no_std"]
categories = ["encoding", "no-std", "embedded", "parser-implementations", "compression"]
exclude = [".github/", "ci/", "/Cargo.lock", "/rust-toolchain.toml"]

[features]
default = ["alloc", "std"]
alloc = ["serde/alloc"]
std = ["alloc"]

[dependencies]
serde = { version = "1", default-features = false }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
zstd = "0.13"

[lib]
name = "serde_zap"
